import React from 'react';

import HtmlSlidePreview from './HtmlSlidePreview';

const SlidePreview = ({ data }) => {
  if (!data) return null;

  // Prefer HTML Slide if available (Designer V2)
  if (data.htmlCode) {
      return <HtmlSlidePreview htmlContent={data.htmlCode} />;
  }

  const { slideHeader, header, title, slideTitle, bullets, visualSuggestion, visualReasoning, actionTitle, topicLabel } = data;

  // Handle both old (slideHeader/header) and new (actionTitle) field names for compatibility
  const displayHeader = actionTitle || header || slideHeader || "Untitled Slide";
  const displayTitle = topicLabel || title || slideTitle || "Strategic Overview";

  return (
    <div className="group relative rounded-2xl overflow-hidden bg-white shadow-xl transition-all duration-300 hover:shadow-2xl border border-white/50 ring-1 ring-gray-100 max-w-2xl mt-4">
        {/* Decorative Top Gradient */}
        <div className="h-2 bg-gradient-to-r from-primary to-primary-light" />

        {/* Header Bar */}
        <div className="bg-slate-950 px-8 py-5 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full -translate-y-1/2 translate-x-1/2 blur-2xl" />
            <h2 className="text-white text-xl font-display font-medium leading-snug tracking-wide relative z-10">
                {displayHeader}
            </h2>
        </div>

        {/* Body */}
        <div className="p-8 bg-gradient-to-b from-white to-gray-50/30">
            {/* Sub-Header / Topic */}
            <h3 className="text-primary font-display text-2xl font-bold mb-6 pb-2 inline-flex items-center gap-3">
                {displayTitle}
                <div className="h-px bg-primary/20 flex-1 w-12" />
            </h3>

            {/* Bullets */}
            <ul className="space-y-4 mb-10">
                {bullets && bullets.map((bullet, idx) => (
                    <li key={idx} className="flex gap-4 text-gray-700 text-sm leading-relaxed group/item hover:text-slate-900 transition-colors">
                        <span className="text-accent font-bold text-lg leading-none mt-0.5 transform transition-transform group-hover/item:scale-110">›</span>
                        <span className="font-medium opacity-90">{bullet}</span>
                    </li>
                ))}
            </ul>

            {/* Visual Suggestion Footer */}
            <div className="mt-4 border border-blue-100 bg-blue-50/50 rounded-xl p-5 flex items-start gap-5 transition-colors hover:bg-blue-50">
                <div className="w-14 h-14 bg-white rounded-2xl shadow-sm flex items-center justify-center text-3xl ring-4 ring-blue-50/50" role="img" aria-label="chart icon">
                    {visualSuggestion?.includes('Waterfall') && '📉'}
                    {visualSuggestion?.includes('Bar') && '📊'}
                    {visualSuggestion?.includes('Pie') && '🥧'}
                    {visualSuggestion?.includes('Process') && '➡️'}
                    {visualSuggestion?.includes('Tree') && '🌳'}
                    {visualSuggestion?.includes('Timeline') && '📅'}
                    {visualSuggestion?.includes('Key Takeaways') && '📝'}
                    {(!visualSuggestion || (!visualSuggestion.includes('Waterfall') && !visualSuggestion.includes('Bar') && !visualSuggestion.includes('Pie') && !visualSuggestion.includes('Process') && !visualSuggestion.includes('Tree') && !visualSuggestion.includes('Timeline') && !visualSuggestion.includes('Key Takeaways'))) && '💡'}
                </div>
                <div className="flex-1">
                    <div className="text-[10px] font-bold text-primary-light uppercase tracking-widest mb-1">Recommended Visualization</div>
                    <div className="text-slate-900 font-bold text-lg tracking-tight mb-2">{visualSuggestion || "Standard Layout"}</div>
                    {visualReasoning && (
                        <div className="text-xs text-gray-500 italic leading-relaxed bg-white/50 p-2 rounded-lg border border-blue-50/50">
                            {visualReasoning}
                        </div>
                    )}
                </div>
            </div>
        </div>
        
        {/* Footer Brand */}
        <div className="px-8 py-3 bg-gray-50 border-t border-gray-100 flex justify-between items-center text-[10px] text-gray-400">
            <span>Generated by Project C</span>
            <span className="uppercase tracking-widest font-semibold opacity-50">Confidential</span>
        </div>
    </div>
  );
};

export default SlidePreview;
